# Generated by Django 5.1.7 on 2025-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.CharField(max_length=100)),
                ('landlord_address', models.CharField(max_length=255)),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_address', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_term', models.CharField(max_length=100)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_date', models.DateField()),
                ('witness1_name', models.CharField(max_length=100)),
                ('witness2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('landlord_signature', models.TextField()),
                ('tenant_signature', models.TextField()),
                ('witness1_signature', models.TextField()),
                ('witness2_signature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BondPaper',
        ),
    ]
