# Generated by Django 5.1.7 on 2025-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_rentagreement_delete_bondpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerOfAttorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_address', models.CharField(max_length=255)),
                ('attorney_name', models.CharField(max_length=100)),
                ('attorney_address', models.CharField(max_length=255)),
                ('witness1_name', models.CharField(max_length=100)),
                ('witness1_address', models.CharField(max_length=255)),
                ('witness2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness2_address', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_signature', models.TextField()),
                ('attorney_signature', models.TextField()),
                ('witness1_signature', models.TextField()),
                ('witness2_signature', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
