# Generated by Django 5.1.7 on 2025-03-26 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_powerofattorney'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastWillAndTestament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('executor_name', models.CharField(max_length=100)),
                ('alternate_executor', models.CharField(blank=True, max_length=100, null=True)),
                ('witness1_name', models.CharField(max_length=100)),
                ('witness1_address', models.CharField(max_length=255)),
                ('witness2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness2_address', models.CharField(blank=True, max_length=255, null=True)),
                ('funeral_wishes', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('testator_signature', models.TextField()),
                ('executor_signature', models.TextField()),
                ('witness1_signature', models.TextField()),
                ('witness2_signature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ndaform',
            old_name='party1',
            new_name='disclosing_party',
        ),
        migrations.RenameField(
            model_name='ndaform',
            old_name='business_project',
            new_name='disclosing_signature',
        ),
        migrations.RenameField(
            model_name='ndaform',
            old_name='party2',
            new_name='jurisdiction',
        ),
        migrations.RenameField(
            model_name='ndaform',
            old_name='confidential_info',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='ndaform',
            old_name='state',
            new_name='receiving_party',
        ),
        migrations.RenameField(
            model_name='ndaform',
            old_name='signature',
            new_name='receiving_signature',
        ),
        migrations.AddField(
            model_name='ndaform',
            name='disclosing_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndaform',
            name='receiving_address',
            field=models.CharField(default='Not Provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndaform',
            name='witness1_name',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndaform',
            name='witness1_signature',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndaform',
            name='witness2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ndaform',
            name='witness2_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
