# Generated by Django 5.1.7 on 2025-03-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_lastwillandtestament_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NDAForm',
        ),
    ]
