# Generated by Django 5.1.7 on 2025-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_delete_ndaform'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDAForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('disclosing_party', models.CharField(max_length=100)),
                ('disclosing_address', models.CharField(max_length=255)),
                ('receiving_party', models.CharField(max_length=100)),
                ('receiving_address', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('witness1_name', models.CharField(max_length=100)),
                ('witness2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disclosing_signature', models.TextField()),
                ('receiving_signature', models.TextField()),
                ('witness1_signature', models.TextField()),
                ('witness2_signature', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
