# Generated by Django 5.1.7 on 2025-03-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_ndaform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndaform',
            name='disclosing_signature',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='ndaform',
            name='receiving_signature',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='ndaform',
            name='witness1_signature',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='ndaform',
            name='witness2_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
