# Generated by Django 5.1.7 on 2025-03-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_alter_ndaform_disclosing_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndaform',
            name='disclosing_signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ndaform',
            name='receiving_signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ndaform',
            name='witness1_signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ndaform',
            name='witness2_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
